from Organizmy.Wilk import Wilk
from Organizmy.Antylopa import  Antylopa
from Organizmy.Owca import Owca
from Organizmy.Lis import Lis
from Organizmy.Zolw import Zolw
from Organizmy.Trawa import Trawa
from Organizmy.Mlecz import Mlecz
from Organizmy.Guarana import Guarana
from Organizmy.Wilcze_jagody import Wilcze_jagody
from Organizmy.Barszcz_sosnowskiego import Barszcz_sosnowskiego